### ISSUE TITLE
deep freeze only part of state

### ISSUE THREAD

**Issue by AngelKyriako** [brandonroberts/ngrx-store-freeze#16]
Assuming a state:
```js
const reducers = {
  router: routerReducer,
  dashboard: dashboardReducer,
  auth: authReducer,
  streams: streamsReducer
}
interface State {
  router: RouterState;
  dashboard: DashboardState;
  auth: AuthState;
  streams: StreamsState;
}
```
Each key is handled by its own reducer and they are combined in dev mode as shown below.
```js
const developmentReducer: ActionReducer<State> = compose(storeFreeze, combineReducers)(reducers);
```
I was wondering if there is a way to use the store freeze, only for certain reducers.

For example:
```js
const pureReducers = {
  router: routerReducer,
  dashboard: dashboardReducer,
  auth: authReducer
}
const mutableReducers = {
  streams: streamsReducer
}

interface State {
  router: RouterState;
  dashboard: DashboardState;
  auth: AuthState;
  streams: StreamsState;
}

// Something like this.
const protectedPureReducers = compose(storeFreeze, combineReducers)(pureReducers)

const developmentReducer: ActionReducer<State> = combineReducers({
  ...protectedPureReducers,
  ...mutableReducers
});
```

Is this even possible with the current API ?

I have to make a choice whether to use ngrx for my mutable state or use some other type of store for it. 

The mutable state changes in an immutable way for UI related updates. For example, addition of a stream to the streams array (inside the reducer).

It is only mutated for low level details that are irrelevant with the UI. For example each stream element of the array can have certain properties mutated at any moment (outside of the reducer).

For those reasons, it does not seem a bad idea to me.
Opposing opinions on this are most welcome, since they might point me to problems that I cannot see at the moment.

**Comment by crysislinux** [comment]
I have the same problem. some injectors are saved in the store. it should be mutable.  I guess for those none serializable states, there is a possibility that they are mutable.

**Comment by AngelKyriako** [comment]
There is no problem with saving mutable state in the store.

The problem is that you cannot deep freeze the part of state that is pure in development mode.
Thats what the issue is about.

By deactivating the deepfreeze you are good to go.

**Comment by brandonroberts** [comment]
You can create a meta-reducer that wraps `storeFreeze` to selectively freeze based on the action type. I'm going to add a built-in API to blacklist/whitelist freezing of state in future release. Working example with current code below to ignore actions dispatched by `@ngrx/router-store` version 4.x.

```ts
import { ActionReducer, MetaReducer } from '@ngrx/store';
import { storeFreeze } from 'ngrx-store-freeze';

export function freezer(reducer: ActionReducer<State>): ActionReducer<State> {
  const exclusions: RegExp[] = [
    /^ROUTER_/
  ];

  return function(state: State, action: any): State {
    const excluded = exclusions.reduce((current, next) => {
      const isExcluded = Boolean(action.type.match(next));

      return current || isExcluded;
    }, false);

    if (excluded) {
      return reducer(state, action);
    }

    return storeFreeze(reducer)(state, action);
  };
}

export const metaReducers: MetaReducer<State>[] = !environment.production ? [freezer] : [];
```

**Comment by osnoser1** [comment]
I have in some of my actions a route object of the ActivatedRoute type, my solution in ngrx 7 thanks to @brandonroberts  was the following:

```javascript
export function freezer(reducer: ActionReducer<any>): ActionReducer<any> {
  const exclusions: RegExp[] = [/^@ngrx\/router-store\//, /^\[Router\]/];

  function hasActivatedRoute(action: Action & { payload?: any }) {
    return (action.payload && action.payload.route) || false;
  }

  return function(state: any, action: Action): any {
    const excluded = exclusions.reduce((current, next) => {
      const isExcluded = Boolean(action.type.match(next)) || hasActivatedRoute(action);
      return current || isExcluded;
    }, false);

    if (excluded) {
      return reducer(state, action);
    }

    return storeFreeze(reducer)(state, action);
  };
}
```
