### ISSUE TITLE
Freezing the payload can make application crash, expecially with RouterStore

### ISSUE THREAD

**Issue by lucax88x** [brandonroberts/ngrx-store-freeze#23]
**I'm already using a CustomStateRouterSerializer, the problem does not rely on the state but on the payload.**

Example, when I get a RouterError, it's putting some weirds objects on the Paylod, and we get this.

![image](https://user-images.githubusercontent.com/6294464/34151881-06964eda-e4ad-11e7-82a3-13c37b5555a4.png)

I noticed this [PR ](https://github.com/brandonroberts/ngrx-store-freeze/pull/2) but I'm struggling trying to understand the point.

I imagine that if in the state we have a reference to the User object, when we freeze the State we also freeze the user object.. correct me if I'm wrong, but the [original redux-freeze does not freeze the payload](https://github.com/buunguyen/redux-freeze/blob/master/src/middleware.js).

If we want to keep this feature (payload freeze), what about having some possibility to filter actions on deepfreezing it, for example filtering on the state type (so I can filter the RouterError, etc.)

Thanks in advance and keep up with the great work!

**Comment by sandangel** [comment]
I have same problem here although i'm not mutating payload:
```ts
const updates = action.payload
        .filter(item => item.unixTime in state.entities)
        .map(item => ({id: item.unixTime, changes: item}));
      const inserts = action.payload.filter(item => !(item.unixTime in state.entities));
      return {
        ...coilEntityAdapter.addMany(inserts, coilEntityAdapter.updateMany(updates, state)),
        loading: false,
        loaded: true,
        errorMess: null,
      };
```

**Comment by brandonroberts** [comment]
This issue has already been fixed in `@ngrx/router-store`
