### ISSUE TITLE
Incorrect example in readme

### ISSUE THREAD

**Issue by fedorl** [brandonroberts/ngrx-store-freeze#24]
In readme example, shouldn't `StoreModule.forRoot(reducers, { metaReducers }),`  be `StoreModule.forRoot(reducers, { metaReducers: metaReducers }),`?

**Comment by fedorl** [comment]
The readme still shows incorrect StoreModule.forRoot(reducers, { metaReducers }) code, not sure why it was closed.

**Comment by brandonroberts** [comment]
The example is not incorrect because the two are equivalent. Its object shorthand for property names.

**Comment by fedorl** [comment]
You are right in the sense that it would work in this particular case, incorrect probably is not the proper wording. Still,  I think it is a bad practice assuming the same name for property in parameter type and a variable/const name completely unrelated to parameters type, especially in library example doc. If metaReducers is renamed differently in an application, say, appMetaReducers, this shorthand will be broken.

**Comment by brandonroberts** [comment]
That's what type checking is for. The options object does not include an `appMetaReducers` object property and would throw a compile time error.

**Comment by fedorl** [comment]
I would not argue, technically you are right and this is minor. But note, with full syntax, rename refactoring will not cause any problem, it would just work without any compile error and developer time or attention. I think given two alternatives more robust and safer one is a better practice and library examples deserve such one )

**Comment by brandonroberts** [comment]
I can agree with that. Care to submit a PR for the minor change?
