### ISSUE TITLE
wrongly freeze when an object which has a getter is in the store

### ISSUE THREAD

**Issue by cedvdb** [brandonroberts/ngrx-store-freeze#25]
Basically what I have is this

```
 abstract class BaseFilter {
    static filterName = 'Base';

	constructor(public value: any) {
	}

	get displayName() {
		return `${(this.constructor as any).filterName}: ${this.value}`;
	}

}

class FilterSort extends BaseFilter {
    static filterName = 'Sort';

    constructor(value: any, public order: 'ASC' | 'DESC') {
		super(value);
	}

	get displayName() {
		return `Sort by: ${this.value} ${this.order.toLowerCase()}`;
	}
}

let a = new FilterSort('lol', 'ASC');

console.log(a.displayName)
```

The above code doesn't work as `this.value` in the getter will somehow be undefined in some cases. Not all cases though, I'm not sure why as I don't have time to pin point the issue. It's resolved by changing the getter to a method call instead.

**Comment by brandonroberts** [comment]
Objects in the store should be POJOs so they can be serialized and frozen correctly. Getters cannot be serialized.
