### ISSUE TITLE
ngrx store freeze error

### ISSUE THREAD

**Issue by sbkpilot1** [brandonroberts/ngrx-store-freeze#30]
I am trying to implement ngrx-store-freeze@0.2.1 to our project and i'm getting this error on app startup:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot add property _resolvedData, object is not extensible
TypeError: Cannot add property _resolvedData, object is not extensible
    at MapSubscriber.eval [as project] (router.js:3909)
    at MapSubscriber._next (map.js:79)
    at MapSubscriber.Subscriber.next (Subscriber.js:92)
    at ScalarObservable._subscribe (ScalarObservable.js:51)
    at ScalarObservable.Observable._trySubscribe (Observable.js:172)
    at ScalarObservable.Observable.subscribe (Observable.js:160)
    at MapOperator.call (map.js:57)
```

Any ideas?  My store is configured like so:

`StoreModule.forRoot(<any>{app: appReducer}, { metaReducers: metaReducers, initialState: initialState })`

**Comment by kanafghan** [comment]
@sbkpilot1 are you using `@ngrx/router-store` and have you implemented your own custom serializer for the `RouterStateSnapshot`? (see https://github.com/brandonroberts/ngrx-store-freeze/blob/master/docs/docs.md#additional-documentation)

**Comment by envil** [comment]
You have to provide `RouterStateSerializer`:

```
@NgModule({
  ...
  providers: [
    { provide: RouterStateSerializer, useClass: CustomRouterStateSerializer}
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

You can find one implementation here: https://github.com/ngrx/platform/blob/master/example-app/app/shared/utils.ts

**Comment by ghost** [comment]
For anyone using @envil's answer, the link has moved with more documentation: https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer
