### ISSUE TITLE
Required Ngrx/store version 6.0.0-beta.1

### ISSUE THREAD

**Issue by MattiJarvinen-BA** [brandonroberts/ngrx-store-freeze#37]
Is there a reason why ngrx-store-freeze is still requiring `@ngrx/store` beta version?

https://github.com/brandonroberts/ngrx-store-freeze/blob/79cac4ee7d75a89fe3d4a28ddb5225d315e2f9f7/package.json#L53

**Comment by brandonroberts** [comment]
There isn't a specific reason. The dependencies just need to be updated for the official release.
