### ISSUE TITLE
TypeError: Cannot add property, object is not extensible

### ISSUE THREAD

**Issue by dherges** [brandonroberts/ngrx-store-freeze#39]
Related to #30

```
core.js:1673 ERROR TypeError: Cannot add property ad9228ca-0730-4cf2-816b-bddfc0468053, object is not extensible
    at reducer (http://localhost:4444/u/wound/main.js:5612:46)
    at combination (http://localhost:4444/u/wound/vendor.js:87606:35)
    at http://localhost:4444/u/wound/main.js:9619:16
    at freeze (http://localhost:4444/u/wound/vendor.js:137521:25)
    at computeNextEntry (http://localhost:4444/u/wound/vendor.js:86938:21)
    at recomputeStates (http://localhost:4444/u/wound/vendor.js:86969:15)
    at http://localhost:4444/u/wound/vendor.js:87198:30
    at ScanSubscriber.StoreDevtools.liftedAction$.pipe.Object.state [as accumulator] (http://localhost:4444/u/wound/vendor.js:87263:38)
    at ScanSubscriber.push.../../node_modules/rxjs/_esm5/internal/operators/scan.js.ScanSubscriber._tryNext (http://localhost:4444/u/wound/vendor.js:145775:27)
    at ScanSubscriber.push.../../node_modules/rxjs/_esm5/internal/operators/scan.js.ScanSubscriber._next (http://localhost:4444/u/wound/vendor.js:145768:25)
```

I have imolemented thhe custom serializer as suggested in #30. The error above is caused by another object but I didn't figure out yet why it's not extensible.

See [MDN docs on "Can't define property, object not extensible"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_define_property_object_not_extensible)

#### Current Behaviour

When the above error occurs, the Angular app gets "stuck" and subsequent actions aren't properly dispatched to the store.

Thus I can click through component views in my app but the state gets broken.

Is it a good error to only print the error to the console? But not throw the error so that the app continues to work?!?

**Comment by dherges** [comment]
**Solved as usage failure / implementation error**

Previous reducer:

```ts
    case Types.FETCH_MAPPING_SUCCESS: {
      const mappings = state.mappings;
      mappings[action.payload.version] = action.payload;

      return {
        ...state,
        mappings
      };
    }
```

Accessed mappings from the state which are frozen objects. Solved with destructuring:

```ts
    case Types.FETCH_MAPPING_SUCCESS: {
      const mappings = { ...state.mappings };
      mappings[action.payload.version] = action.payload;

      return {
        ...state,
        mappings
      };
    }
```

**Comment by dherges** [comment]
I wonder whether it's possible to include in the error message which action dispatched to the store/reducer causes the error?!?

**Comment by marc-wilson** [comment]
This error is super misleading. There should be something in the error message that states something like "hey, code monkey. You can't update something in the store directly". Spent hours trying to figure out what could be causing this issue only to find out it's because I was doing this:

```
on(ApplicationActions.toggleCollapseNavGroup, (state, group: INavGroup ) => {
    const navGroup = state.allNavGroups.find( g => g.groupId === group.groupId);
    navGroup.collapsed = !navGroup.collapsed;
    return { ...state };
  })
```

btw, I tried destructuring trick. It did not work. Same error.

```
const navGroups = [ ...state.allNavGroups ];
const navGroup = navGroups.find( g => g.groupId === group.groupId);
navGroup.collapsed = !navGroup.collapsed;
return { ...state, allNavGroups: navGroups };
```

But if I do this, it works:

`const navGroups = state.allNavGroups.map(g => ({ ...g }));`
