### ISSUE TITLE
Issue with payload freeze with @ngrx/router-store actions

### ISSUE THREAD

**Issue by cmdickson** [brandonroberts/ngrx-store-freeze#5]
The recent changes to freeze the payload cause an issue when using the @ngrx/router-store library.  
A number of the actions made available by that library allow for the `NavigationExtras` to be included in the action payload.  One of those values can be the `ActivatedRoute`:

```
constructor(private _route: ActivatedRoute) {}
... 
someFunction(route: string): void {
    this._store.dispatch(go([route], {}, {relativeTo: this._route}));
}
```

When the go action is processed by the store reducers, the properties of the `ActivatedRoute`, including `Observables` etc, get frozen, which causes all sorts of errors later on.

Not sure if this is really an issue with this library, or bad practice to include these sorts of objects in the action payload.  Just thought I'd bring it to your attention.

**Comment by tsm91** [comment]
@KwintenP what do you think? @cmdickson is talking about https://github.com/codewareio/ngrx-store-freeze/pull/2

As i stated [here](https://github.com/codewareio/ngrx-store-freeze/issues/7#issuecomment-267318477) I dont use ngrx / redux architecture anymore. I don't have the insight but i want to close this. We need a decision.

**Comment by brandonroberts** [comment]
The `ActivatedRoute` is a complex object with circular references, so it cannot be frozen. To get around this, you need to exclude these actions from being frozen by this library.
